// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtmhKIG9lEeDeGYrV4V7cf4dzyEBaF-0',
    appId: '1:862251787565:web:2248bcabc8bc9ca8c59fa4',
    messagingSenderId: '862251787565',
    projectId: 'futsal-182fe',
    authDomain: 'futsal-182fe.firebaseapp.com',
    storageBucket: 'futsal-182fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kPNQMrboCYK1RsgId_O1QveZNWxuxz4',
    appId: '1:862251787565:android:8fa82841126c5d4bc59fa4',
    messagingSenderId: '862251787565',
    projectId: 'futsal-182fe',
    storageBucket: 'futsal-182fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ADaEd6ghjJPMAk2aCLyhR6sNhWBNkL4',
    appId: '1:862251787565:ios:896000e889c3d078c59fa4',
    messagingSenderId: '862251787565',
    projectId: 'futsal-182fe',
    storageBucket: 'futsal-182fe.firebasestorage.app',
    iosClientId: '862251787565-iak3ledtr8dbcdhkknv7s090884p56tu.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
