// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/views/players_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:myapp/models/models.dart' as _i3;
import 'package:myapp/services/data_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i2.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Player> get players =>
      (super.noSuchMethod(
            Invocation.getter(#players),
            returnValue: <_i3.Player>[],
          )
          as List<_i3.Player>);

  @override
  List<_i3.SuggestedTeam> get suggestedTeams =>
      (super.noSuchMethod(
            Invocation.getter(#suggestedTeams),
            returnValue: <_i3.SuggestedTeam>[],
          )
          as List<_i3.SuggestedTeam>);

  @override
  bool get isLoadingPlayers =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingPlayers),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoadingRoster =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingRoster),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoadingSuggestedTeams =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingSuggestedTeams),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setLatestRosterForTest(_i3.WeeklyRoster? roster) => super.noSuchMethod(
    Invocation.method(#setLatestRosterForTest, [roster]),
    returnValueForMissingStub: null,
  );

  @override
  String generateTeamHash(List<List<_i3.Player>>? teams) =>
      (super.noSuchMethod(
            Invocation.method(#generateTeamHash, [teams]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#generateTeamHash, [teams]),
            ),
          )
          as String);

  @override
  _i5.Future<void> fetchPlayers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlayers, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> addPlayer(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addPlayer, [name]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> deletePlayer(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlayer, [playerId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> submitRoster(
    List<String>? playerIds,
    int? numberOfTeams,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitRoster, [playerIds, numberOfTeams]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> fetchLatestRoster({bool? forceFromServer = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestRoster, [], {
              #forceFromServer: forceFromServer,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchSuggestedTeams() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSuggestedTeams, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> vote(
    _i3.SuggestedTeam? suggestion,
    String? userId,
    String? voteType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#vote, [suggestion, userId, voteType]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> submitSuggestedTeam(
    List<List<_i3.Player>>? teams,
    String? rosterId,
    String? username,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitSuggestedTeam, [
              teams,
              rosterId,
              username,
              userId,
            ]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
